// Snake Rush — Client-Hosted Multiplayer Simulation
//
// This is server.js's Room class, ported to run in the browser instead of
// on a Node server. Architecture-wise nothing about "who is authoritative"
// changed — one participant (the WebRTC host) still runs the one true
// simulation and broadcasts state to everyone else, exactly like the old
// Node server did. What changed is WHERE that authoritative copy runs: on
// the host player's own device instead of a dedicated Render server.
//
// This trade-off was chosen deliberately (see net.js for the connection
// side of it): it removes Render's free-tier CPU throttling entirely,
// at the cost of the match now depending on the host's device staying
// awake and connected — if the host's browser tab dies or their network
// drops, the match ends for everyone, the same way unplugging a LAN
// party's host machine would. There is no separate always-on server
// anymore for a match to fall back to.
//
// Port notes vs. server.js:
//   - No `ws`/`http`/`crypto` (Node-only) — WebRTC send/receive is owned
//     by net.js, this file only produces/consumes plain JS objects.
//   - `crypto.randomInt` → `Math.random()`-based (room codes are now
//     generated by net.js/PeerJS, not here, so makeRoomCode() is gone
//     entirely — this file no longer knows about room codes at all).
//   - Room.destroy()'s `clearInterval` becomes Simulation.stop(), called
//     when the host leaves/closes the match.
//   - _broadcastState() no longer touches WebSocket directly — it calls
//     this.onState(payload), a callback the host-side mp.js wires up to
//     Net.send(). Everything upstream of that call is untouched from
//     server.js.
//   - setInput()/addPlayer()/removePlayer() are unchanged in spirit but
//     no longer take a `ws` handle — the host's own input goes straight
//     into this simulation via a direct method call (no loopback network
//     hop needed since host and simulation are the same device), and
//     peer input arrives already-deserialized from net.js's message bus.

'use strict';

// ── World / tuning constants — identical to server.js. If server.js is
// ever updated (e.g. re-deployed as a fallback dedicated-server mode),
// these two files need to be kept in sync by hand; there is no shared
// import between them since one runs in Node and one in the browser.
const SIM_WORLD_W = 4000;
const SIM_WORLD_H = 4000;
const SIM_TICK_RATE = 20;                  // simulation steps per second
const SIM_TICK_MS = 1000 / SIM_TICK_RATE;

// Static mode: speed is constant, not length-scaled — length is fixed at
// START_LEN for the whole match (food is score-only, see the food-eat
// handler), so there's nothing for speed to scale against.
const SIM_BASE_SPEED = 190;                // world units/sec — matches single-player BASE_SPEED
const SIM_BOOST_SPEED = 300;               // matches single-player BOOST_SPEED
const SIM_SEGMENT_GAP = 8;                 // matches single-player SEGMENT_GAP
const SIM_SEGMENT_R = 10;
const SIM_START_LEN = 8;
const SIM_FOOD_COUNT = 80;
const SIM_FOOD_R = 6;
const SIM_MAX_PLAYERS = 4;                 // headroom above the requested 2-3

const SIM_PLAYER_LIVES = 3;
const SIM_RESPAWN_DELAY = 2;               // seconds a dead player waits before respawning
const SIM_POINTS_PER_FOOD = 1;
const SIM_POINTS_PER_KILL = 10;
const SIM_LIFELINE_SPAWN_CHANCE = 0.01;    // rolled once whenever a food item respawns
const SIM_LIFELINE_MAX_ON_MAP = 1;

const SIM_AI_COUNT = 4;
const SIM_AI_START_LEN = 10;
const SIM_AI_SPEED_MUL = 0.85;
const SIM_AI_AVOID_RADIUS = 70;
const SIM_AI_WANDER_TURN_INTERVAL = [2, 5];
const SIM_AI_STEER_EVERY_N_TICKS = 3;
const SIM_AI_RESPAWN_DELAY = 4;
const SIM_AI_NAMES = [
  'Viper', 'Zigzag', 'Nibbles', 'Slither', 'Fang', 'Coil', 'Scales',
  'Rattler', 'Whiskers', 'Noodle', 'Zippy', 'Dash', 'Shadow', 'Comet',
];
// Must exactly match the free/always-unlocked skin IDs in game_part1.js's
// SKINS_DEF — kept as a plain string list rather than importing that
// file, same reasoning as server.js had.
const SIM_AI_SKIN_POOL = ['multicolour', 'fatty', 'thin', 'designer'];

const SIM_PLAYER_COLORS = ['#39ff6a', '#ff5f9e', '#2fb8ff', '#ffb300'];
const SIM_AI_COLORS = ['#c47eff', '#ff9a5c', '#5cd6c4', '#e0e05c', '#ff7e9e', '#7ea8ff'];

function simClamp(v, min, max) { return Math.max(min, Math.min(max, v)); }

function simRandomFoodPos() {
  return {
    x: 40 + Math.random() * (SIM_WORLD_W - 80),
    y: 40 + Math.random() * (SIM_WORLD_H - 80),
  };
}

// ─────────────────────────────────────────────────────────────
// Simulation — one shared world. Holds all players' snakes + food, runs
// its own tick loop (via setInterval, same as server.js's Room did), and
// hands the resulting state to whatever onState callback the host wired
// up (instead of writing to WebSocket sockets directly).
// ─────────────────────────────────────────────────────────────
class Simulation {
  constructor() {
    this.players = new Map();   // playerId -> { snake, name } — real humans only
    this.entities = new Map();  // id -> snake — EVERY snake (players + AI)
    this.food = [];
    for (let i = 0; i < SIM_FOOD_COUNT; i++) {
      this.food.push({ id: i, ...simRandomFoodPos() });
    }
    this._nextFoodId = SIM_FOOD_COUNT;
    this._usedAIColors = 0;
    this._lifelineCount = 0;
    this._aiTickCounter = 0;

    // Called with the { type: 'state', food, snakes } payload every tick
    // — the host's mp.js sets this to something that forwards the
    // payload to Net.send(). Left as a no-op by default so the
    // simulation can run (e.g. for local testing) without a network
    // layer attached yet.
    this.onState = () => {};

    this._spawnAISnakes();
    this._tickHandle = null;
  }

  start() {
    if (this._tickHandle) return; // already running
    this._tickHandle = setInterval(() => this._tick(), SIM_TICK_MS);
  }

  stop() {
    if (this._tickHandle) clearInterval(this._tickHandle);
    this._tickHandle = null;
  }

  isEmpty() { return this.players.size === 0; }

  _makeSnake(id, x, y, name, color) {
    const segments = [];
    for (let i = 0; i < SIM_START_LEN; i++) segments.push({ x: x - i * SIM_SEGMENT_GAP, y });
    return {
      id, name, x, y,
      dirX: 1, dirY: 0,
      inputDirX: 1, inputDirY: 0,
      boosting: false,
      alive: true,
      length: SIM_START_LEN,
      score: 0,
      segments,
      color,
      isAI: false,
    };
  }

  // playerId here is whatever net.js uses to identify a peer — the
  // host's own local player gets a fixed id (see host-side mp.js), and
  // each connected guest gets their PeerJS connection's peer id.
  addPlayer(playerId, name, skin) {
    const spawn = simRandomFoodPos();
    const color = SIM_PLAYER_COLORS[this.players.size % SIM_PLAYER_COLORS.length];
    const snake = this._makeSnake(playerId, spawn.x, spawn.y, name || 'Player', color);
    snake.skin = typeof skin === 'string' && skin ? skin : 'multicolour';
    snake.lives = SIM_PLAYER_LIVES;
    snake._respawnTimer = 0;
    this.players.set(playerId, { snake, name });
    this.entities.set(playerId, snake);
    return snake;
  }

  removePlayer(playerId) {
    this.players.delete(playerId);
    this.entities.delete(playerId);
  }

  _spawnAISnakes() {
    for (let i = 0; i < SIM_AI_COUNT; i++) {
      this._spawnOneAI(`ai-${i}`);
    }
  }

  _spawnOneAI(id) {
    const spawn = simRandomFoodPos();
    const name = SIM_AI_NAMES[Math.floor(Math.random() * SIM_AI_NAMES.length)];
    const color = SIM_AI_COLORS[this._usedAIColors % SIM_AI_COLORS.length];
    this._usedAIColors++;
    const snake = this._makeSnake(id, spawn.x, spawn.y, name, color);
    snake.isAI = true;
    snake.length = SIM_AI_START_LEN;
    snake.skin = SIM_AI_SKIN_POOL[Math.floor(Math.random() * SIM_AI_SKIN_POOL.length)];
    snake._wanderT = Math.random() * 10;
    snake._nextWanderChange = 0;
    this.entities.set(id, snake);
    return snake;
  }

  setInput(playerId, dirX, dirY, boosting) {
    const p = this.players.get(playerId);
    if (!p || !p.snake.alive) return;
    // Normalize here — never trust the sender's magnitude, only
    // direction, whether that sender is a remote peer or the host's own
    // local input path.
    const len = Math.hypot(dirX, dirY);
    if (len > 0.0001) {
      p.snake.inputDirX = dirX / len;
      p.snake.inputDirY = dirY / len;
    }
    p.snake.boosting = !!boosting;
  }

  _tick() {
    const dt = SIM_TICK_MS / 1000;

    this._aiTickCounter = (this._aiTickCounter + 1) % SIM_AI_STEER_EVERY_N_TICKS;
    if (this._aiTickCounter === 0) {
      for (const snake of this.entities.values()) {
        if (!snake.alive || !snake.isAI) continue;
        this._steerAI(snake, dt * SIM_AI_STEER_EVERY_N_TICKS);
      }
    }

    for (const snake of this.entities.values()) {
      if (!snake.alive) continue;

      const turnRate = Math.min(1, 0.12 * dt * 60);
      snake.dirX += (snake.inputDirX - snake.dirX) * turnRate;
      snake.dirY += (snake.inputDirY - snake.dirY) * turnRate;
      const dl = Math.hypot(snake.dirX, snake.dirY) || 1;
      snake.dirX /= dl; snake.dirY /= dl;

      const speedMul = snake.isAI ? SIM_AI_SPEED_MUL : 1;
      const speed = (snake.boosting ? SIM_BOOST_SPEED : SIM_BASE_SPEED) * speedMul;
      snake.x = simClamp(snake.x + snake.dirX * speed * dt, SIM_SEGMENT_R, SIM_WORLD_W - SIM_SEGMENT_R);
      snake.y = simClamp(snake.y + snake.dirY * speed * dt, SIM_SEGMENT_R, SIM_WORLD_H - SIM_SEGMENT_R);

      snake.segments[0].x = snake.x;
      snake.segments[0].y = snake.y;

      const targetLen = Math.max(SIM_START_LEN, Math.round(snake.length));
      if (snake.segments.length < targetLen) {
        const tail = snake.segments[snake.segments.length - 1];
        snake.segments.push({ x: tail.x, y: tail.y });
      } else if (snake.segments.length > targetLen) {
        snake.segments.length = targetLen;
      }

      const gapSq = SIM_SEGMENT_GAP * SIM_SEGMENT_GAP;
      for (let i = 1; i < snake.segments.length; i++) {
        const seg = snake.segments[i];
        const prev = snake.segments[i - 1];
        const dx = prev.x - seg.x, dy = prev.y - seg.y;
        const dSq = dx * dx + dy * dy;
        if (dSq <= gapSq) continue;
        const dist = Math.sqrt(dSq);
        const t = (dist - SIM_SEGMENT_GAP) / dist;
        seg.x += dx * t;
        seg.y += dy * t;
      }
    }

    // Food collisions
    for (const snake of this.entities.values()) {
      if (!snake.alive) continue;
      for (let i = this.food.length - 1; i >= 0; i--) {
        const f = this.food[i];
        const d = Math.hypot(f.x - snake.x, f.y - snake.y);
        if (d < SIM_SEGMENT_R + SIM_FOOD_R) {
          this.food.splice(i, 1);
          if (f.isLifeline) this._lifelineCount--;

          if (f.isLifeline) {
            if (!snake.isAI && snake.lives < SIM_PLAYER_LIVES) snake.lives += 1;
          } else {
            if (!snake.isAI) snake.score += SIM_POINTS_PER_FOOD;
          }

          const np = simRandomFoodPos();
          const isLifeline = this._lifelineCount < SIM_LIFELINE_MAX_ON_MAP && Math.random() < SIM_LIFELINE_SPAWN_CHANCE;
          if (isLifeline) this._lifelineCount++;
          this.food.push({ id: this._nextFoodId++, ...np, isLifeline });
        }
      }
    }

    // Snake-vs-snake collision
    const hitDistSq = (SIM_SEGMENT_R * 1.3) * (SIM_SEGMENT_R * 1.3);
    const aliveEntities = [...this.entities.values()].filter(s => s.alive);
    for (const a of aliveEntities) {
      for (const b of aliveEntities) {
        if (a.id === b.id) continue;
        if (Math.abs(a.x - b.x) > 400 || Math.abs(a.y - b.y) > 400) continue;

        for (let i = 3; i < b.segments.length; i++) {
          const seg = b.segments[i];
          const dx = seg.x - a.x, dy = seg.y - a.y;
          if (dx * dx + dy * dy < hitDistSq) {
            a.alive = false;
            if (!b.isAI) b.score += SIM_POINTS_PER_KILL;
            break;
          }
        }
        if (!a.alive) break;
      }
    }

    // AI respawn
    for (const snake of this.entities.values()) {
      if (snake.isAI && !snake.alive) {
        snake._respawnTimer = (snake._respawnTimer || 0) + dt;
        if (snake._respawnTimer >= SIM_AI_RESPAWN_DELAY) {
          this.entities.delete(snake.id);
          this._spawnOneAI(snake.id);
        }
      }
    }

    // Player respawn
    for (const { snake } of this.players.values()) {
      if (snake.alive || snake.lives <= 0) continue;
      snake._respawnTimer += dt;
      if (snake._respawnTimer >= SIM_RESPAWN_DELAY) {
        snake.lives -= 1;
        if (snake.lives > 0) {
          const spawn = simRandomFoodPos();
          snake.x = spawn.x; snake.y = spawn.y;
          snake.dirX = 1; snake.dirY = 0;
          snake.inputDirX = 1; snake.inputDirY = 0;
          snake.length = SIM_START_LEN;
          const segs = [];
          for (let i = 0; i < SIM_START_LEN; i++) segs.push({ x: spawn.x - i * SIM_SEGMENT_GAP, y: spawn.y });
          snake.segments = segs;
          snake.alive = true;
        }
        snake._respawnTimer = 0;
      }
    }

    this._broadcastState();
  }

  // Simple 2-state AI brain: AVOID when another snake's body is
  // dangerously close, otherwise WANDER with a slowly-changing random
  // direction. Identical to server.js's version — see that file for the
  // fuller reasoning comment on why SEEK_FOOD/FLEE/PURSUE were left out.
  _steerAI(snake, dt) {
    const avoidRadiusSq = SIM_AI_AVOID_RADIUS * SIM_AI_AVOID_RADIUS;
    let nearestThreatDistSq = Infinity;
    let threatX = 0, threatY = 0;
    for (const other of this.entities.values()) {
      if (other.id === snake.id || !other.alive) continue;
      if (Math.abs(other.x - snake.x) > SIM_AI_AVOID_RADIUS * 2 || Math.abs(other.y - snake.y) > SIM_AI_AVOID_RADIUS * 2) continue;
      for (let i = 0; i < other.segments.length; i += 3) {
        const seg = other.segments[i];
        const dx = seg.x - snake.x, dy = seg.y - snake.y;
        const dSq = dx * dx + dy * dy;
        if (dSq < nearestThreatDistSq) { nearestThreatDistSq = dSq; threatX = seg.x; threatY = seg.y; }
      }
    }
    if (nearestThreatDistSq < avoidRadiusSq) {
      const dx = snake.x - threatX, dy = snake.y - threatY;
      const dl = Math.hypot(dx, dy) || 1;
      snake.inputDirX = dx / dl;
      snake.inputDirY = dy / dl;
      return;
    }

    snake._wanderT += dt;
    if (snake._wanderT >= snake._nextWanderChange) {
      snake._wanderT = 0;
      snake._nextWanderChange = SIM_AI_WANDER_TURN_INTERVAL[0] + Math.random() * (SIM_AI_WANDER_TURN_INTERVAL[1] - SIM_AI_WANDER_TURN_INTERVAL[0]);
      const angle = Math.random() * Math.PI * 2;
      snake.inputDirX = Math.cos(angle);
      snake.inputDirY = Math.sin(angle);
    }
  }

  _broadcastState() {
    const snakes = [...this.entities.values()].map((snake) => ({
      id: snake.id,
      name: snake.name,
      alive: snake.alive,
      length: Math.round(snake.length),
      color: snake.color,
      isAI: !!snake.isAI,
      skin: snake.skin,
      score: snake.score || 0,
      lives: snake.isAI ? null : snake.lives,
      segments: snake.segments,
    }));

    this.onState({ type: 'state', food: this.food, snakes });
  }
}

// Exposed as a plain global — this project doesn't use ES module imports
// for game_part*.js/mp.js, so following that same convention here rather
// than introducing import/export syntax into only this one file.
window.Simulation = Simulation;
window.SIM_MAX_PLAYERS = SIM_MAX_PLAYERS;
